/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package tm.fantom.tmdbvw.api.netmodel;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * InlineResponse20044ProductionCountries
 */

public class InlineResponse20044ProductionCountries {
    @SerializedName("iso_3166_1")
    private String iso31661 = null;

    @SerializedName("name")
    private String name = null;

    public InlineResponse20044ProductionCountries iso31661(String iso31661) {
        this.iso31661 = iso31661;
        return this;
    }

    /**
     * Get iso31661
     *
     * @return iso31661
     **/

    public String getIso31661() {
        return iso31661;
    }

    public void setIso31661(String iso31661) {
        this.iso31661 = iso31661;
    }

    public InlineResponse20044ProductionCountries name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse20044ProductionCountries inlineResponse20044ProductionCountries = (InlineResponse20044ProductionCountries) o;
        return Objects.equals(this.iso31661, inlineResponse20044ProductionCountries.iso31661) &&
                Objects.equals(this.name, inlineResponse20044ProductionCountries.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(iso31661, name);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse20044ProductionCountries {\n");

        sb.append("    iso31661: ").append(toIndentedString(iso31661)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

