/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package tm.fantom.tmdbvw.api.netmodel;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * InlineResponse20044SpokenLanguages
 */

public class InlineResponse20044SpokenLanguages {
    @SerializedName("name")
    private String name = null;

    @SerializedName("iso_639_1")
    private String iso6391 = null;

    public InlineResponse20044SpokenLanguages name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public InlineResponse20044SpokenLanguages iso6391(String iso6391) {
        this.iso6391 = iso6391;
        return this;
    }

    /**
     * Get iso6391
     *
     * @return iso6391
     **/

    public String getIso6391() {
        return iso6391;
    }

    public void setIso6391(String iso6391) {
        this.iso6391 = iso6391;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse20044SpokenLanguages inlineResponse20044SpokenLanguages = (InlineResponse20044SpokenLanguages) o;
        return Objects.equals(this.name, inlineResponse20044SpokenLanguages.name) &&
                Objects.equals(this.iso6391, inlineResponse20044SpokenLanguages.iso6391);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, iso6391);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse20044SpokenLanguages {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    iso6391: ").append(toIndentedString(iso6391)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

