/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package tm.fantom.tmdbvw.api.netmodel;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MoviesResponse
 */

public class MoviesResponse {
    @SerializedName("page")
    private int page;

    @SerializedName("total_pages")
    private int totalPages;

    @SerializedName("results")
    private List<MovieListObject> results = null;

    @SerializedName("total_results")
    private int totalResults;

    private boolean error = false;

    public MoviesResponse page(int page) {
        this.page = page;
        return this;
    }

    /**
     * Get page
     *
     * @return page
     **/

    public int getPage() {
        return page;
    }

    public void setPage(int page) {
        this.page = page;
    }

    public MoviesResponse totalPages(int totalPages) {
        this.totalPages = totalPages;
        return this;
    }

    /**
     * Get totalPages
     *
     * @return totalPages
     **/

    public int getTotalPages() {
        return totalPages;
    }

    public void setTotalPages(int totalPages) {
        this.totalPages = totalPages;
    }

    public MoviesResponse results(List<MovieListObject> results) {
        this.results = results;
        return this;
    }

    public MoviesResponse addResultsItem(MovieListObject resultsItem) {
        if (this.results == null) {
            this.results = new ArrayList<MovieListObject>();
        }
        this.results.add(resultsItem);
        return this;
    }

    /**
     * Get results
     *
     * @return results
     **/

    public List<MovieListObject> getResults() {
        return results;
    }

    public void setResults(List<MovieListObject> results) {
        this.results = results;
    }

    public MoviesResponse totalResults(Integer totalResults) {
        this.totalResults = totalResults;
        return this;
    }

    /**
     * Get totalResults
     *
     * @return totalResults
     **/

    public Integer getTotalResults() {
        return totalResults;
    }

    public void setTotalResults(Integer totalResults) {
        this.totalResults = totalResults;
    }

    public boolean isError() {
        return error;
    }

    public MoviesResponse setError(boolean error) {
        this.error = error;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MoviesResponse moviesResponse = (MoviesResponse) o;
        return Objects.equals(this.page, moviesResponse.page) &&
                Objects.equals(this.totalPages, moviesResponse.totalPages) &&
                Objects.equals(this.results, moviesResponse.results) &&
                Objects.equals(this.totalResults, moviesResponse.totalResults);
    }

    @Override
    public int hashCode() {
        return Objects.hash(page, totalPages, results, totalResults);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MoviesResponse {\n");

        sb.append("    page: ").append(toIndentedString(page)).append("\n");
        sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
        sb.append("    results: ").append(toIndentedString(results)).append("\n");
        sb.append("    totalResults: ").append(toIndentedString(totalResults)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

