/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package tm.fantom.tmdbvw.api.netmodel;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MovieListObject
 */

public class MovieListObject {
    @SerializedName("poster_path")
    private String posterPath = null;

    @SerializedName("adult")
    private Boolean adult = null;

    @SerializedName("overview")
    private String overview = null;

    @SerializedName("release_date")
    private String releaseDate = null;

    @SerializedName("genre_ids")
    private List<Integer> genreIds = null;

    @SerializedName("id")
    private int id;

    @SerializedName("original_title")
    private String originalTitle = null;

    @SerializedName("original_language")
    private String originalLanguage = null;

    @SerializedName("title")
    private String title = null;

    @SerializedName("backdrop_path")
    private String backdropPath = null;

    @SerializedName("popularity")
    private float popularity;

    @SerializedName("vote_count")
    private int voteCount;

    @SerializedName("video")
    private Boolean video = null;

    @SerializedName("vote_average")
    private float voteAverage;

    public MovieListObject posterPath(String posterPath) {
        this.posterPath = posterPath;
        return this;
    }

    /**
     * Get posterPath
     *
     * @return posterPath
     **/

    public String getPosterPath() {
        return posterPath;
    }

    public void setPosterPath(String posterPath) {
        this.posterPath = posterPath;
    }

    public MovieListObject adult(Boolean adult) {
        this.adult = adult;
        return this;
    }

    /**
     * Get adult
     *
     * @return adult
     **/

    public Boolean adult() {
        return adult;
    }

    public void setAdult(Boolean adult) {
        this.adult = adult;
    }

    public MovieListObject overview(String overview) {
        this.overview = overview;
        return this;
    }

    /**
     * Get overview
     *
     * @return overview
     **/

    public String getOverview() {
        return overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }

    public MovieListObject releaseDate(String releaseDate) {
        this.releaseDate = releaseDate;
        return this;
    }

    /**
     * Get releaseDate
     *
     * @return releaseDate
     **/

    public String getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(String releaseDate) {
        this.releaseDate = releaseDate;
    }

    public MovieListObject genreIds(List<Integer> genreIds) {
        this.genreIds = genreIds;
        return this;
    }

    public MovieListObject addGenreIdsItem(Integer genreIdsItem) {
        if (this.genreIds == null) {
            this.genreIds = new ArrayList<Integer>();
        }
        this.genreIds.add(genreIdsItem);
        return this;
    }

    /**
     * Get genreIds
     *
     * @return genreIds
     **/

    public List<Integer> getGenreIds() {
        return genreIds;
    }

    public void setGenreIds(List<Integer> genreIds) {
        this.genreIds = genreIds;
    }

    public MovieListObject id(int id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public MovieListObject originalTitle(String originalTitle) {
        this.originalTitle = originalTitle;
        return this;
    }

    /**
     * Get originalTitle
     *
     * @return originalTitle
     **/

    public String getOriginalTitle() {
        return originalTitle;
    }

    public void setOriginalTitle(String originalTitle) {
        this.originalTitle = originalTitle;
    }

    public MovieListObject originalLanguage(String originalLanguage) {
        this.originalLanguage = originalLanguage;
        return this;
    }

    /**
     * Get originalLanguage
     *
     * @return originalLanguage
     **/

    public String getOriginalLanguage() {
        return originalLanguage;
    }

    public void setOriginalLanguage(String originalLanguage) {
        this.originalLanguage = originalLanguage;
    }

    public MovieListObject title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     **/

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public MovieListObject backdropPath(String backdropPath) {
        this.backdropPath = backdropPath;
        return this;
    }

    /**
     * Get backdropPath
     *
     * @return backdropPath
     **/

    public String getBackdropPath() {
        return backdropPath;
    }

    public void setBackdropPath(String backdropPath) {
        this.backdropPath = backdropPath;
    }

    public MovieListObject popularity(float popularity) {
        this.popularity = popularity;
        return this;
    }

    /**
     * Get popularity
     *
     * @return popularity
     **/

    public float getPopularity() {
        return popularity;
    }

    public void setPopularity(float popularity) {
        this.popularity = popularity;
    }

    public MovieListObject voteCount(Integer voteCount) {
        this.voteCount = voteCount;
        return this;
    }

    /**
     * Get voteCount
     *
     * @return voteCount
     **/

    public Integer getVoteCount() {
        return voteCount;
    }

    public void setVoteCount(Integer voteCount) {
        this.voteCount = voteCount;
    }

    public MovieListObject video(Boolean video) {
        this.video = video;
        return this;
    }

    /**
     * Get video
     *
     * @return video
     **/

    public Boolean video() {
        return video;
    }

    public void setVideo(Boolean video) {
        this.video = video;
    }

    public MovieListObject voteAverage(float voteAverage) {
        this.voteAverage = voteAverage;
        return this;
    }

    /**
     * Get voteAverage
     *
     * @return voteAverage
     **/

    public float getVoteAverage() {
        return voteAverage;
    }

    public void setVoteAverage(float voteAverage) {
        this.voteAverage = voteAverage;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MovieListObject movieListObject = (MovieListObject) o;
        return Objects.equals(this.posterPath, movieListObject.posterPath) &&
                Objects.equals(this.adult, movieListObject.adult) &&
                Objects.equals(this.overview, movieListObject.overview) &&
                Objects.equals(this.releaseDate, movieListObject.releaseDate) &&
                Objects.equals(this.genreIds, movieListObject.genreIds) &&
                Objects.equals(this.id, movieListObject.id) &&
                Objects.equals(this.originalTitle, movieListObject.originalTitle) &&
                Objects.equals(this.originalLanguage, movieListObject.originalLanguage) &&
                Objects.equals(this.title, movieListObject.title) &&
                Objects.equals(this.backdropPath, movieListObject.backdropPath) &&
                Objects.equals(this.popularity, movieListObject.popularity) &&
                Objects.equals(this.voteCount, movieListObject.voteCount) &&
                Objects.equals(this.video, movieListObject.video) &&
                Objects.equals(this.voteAverage, movieListObject.voteAverage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(posterPath, adult, overview, releaseDate, genreIds, id, originalTitle, originalLanguage, title, backdropPath, popularity, voteCount, video, voteAverage);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MovieListObject {\n");

        sb.append("    posterPath: ").append(toIndentedString(posterPath)).append("\n");
        sb.append("    adult: ").append(toIndentedString(adult)).append("\n");
        sb.append("    overview: ").append(toIndentedString(overview)).append("\n");
        sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
        sb.append("    genreIds: ").append(toIndentedString(genreIds)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    originalTitle: ").append(toIndentedString(originalTitle)).append("\n");
        sb.append("    originalLanguage: ").append(toIndentedString(originalLanguage)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    backdropPath: ").append(toIndentedString(backdropPath)).append("\n");
        sb.append("    popularity: ").append(toIndentedString(popularity)).append("\n");
        sb.append("    voteCount: ").append(toIndentedString(voteCount)).append("\n");
        sb.append("    video: ").append(toIndentedString(video)).append("\n");
        sb.append("    voteAverage: ").append(toIndentedString(voteAverage)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

